# Generated by Django 3.0.4 on 2020-03-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_App', '0002_auto_20200324_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
