# Generated by Django 3.0.4 on 2020-03-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_App', '0004_user_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_attendance',
            name='exit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
