# Generated by Django 3.0.4 on 2020-03-25 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_App', '0005_auto_20200325_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_attendance',
            name='present_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
