# Generated by Django 3.0.4 on 2020-03-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_App', '0007_auto_20200325_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_attendance',
            old_name='present',
            new_name='is_present',
        ),
    ]
